services:
  web:
    image: web
    build: ./client
    ports:
      - 5173:5173
    depends_on:
        - api
  
    develop:
      watch:
        - path: ./client/package.json
          action: rebuild
        - path: ./client/package-lock.json
          action: rebuild
        - path: ./client
          target: /app
          action: sync

  api:
    image: api
    build: ./server
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://db:27017/professor
    restart: always
    
    develop:
      watch:
        - path: ./server/package.json
          action: rebuild
        - path: ./server/package-lock.json
          action: rebuild
        - path: ./server
          target: /app
          action: sync

  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - professor:/data/db

volumes:
  professor: